language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2  

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-text
  - vendor/bin/behat -c behat.yml
