worldia_textmaster_document_index:
    methods:  [GET]
    pattern:  /projects/{projectId}/documents
    defaults: { _controller: WorldiaTextmasterBundle:Document:index }

worldia_textmaster_document_show:
    methods:  [GET]
    pattern:  /projects/{projectId}/documents/{id}
    defaults: { _controller: WorldiaTextmasterBundle:Document:show }

worldia_textmaster_document_update:
    methods:  [POST]
    pattern:  /projects/{projectId}/documents
    defaults: { _controller: WorldiaTextmasterBundle:Document:callback }
