worldia_textmaster_job_index:
    methods:  [GET]
    path:     /jobs
    defaults: { _controller: 'WorldiaTextmasterBundle:Job:index' }

worldia_textmaster_job_show:
    methods:  [GET]
    path:     /jobs/{id}
    defaults: { _controller: 'WorldiaTextmasterBundle:Job:show' }

worldia_textmaster_job_compare:
    methods:  [GET]
    path:     /jobs/{id}/compare
    defaults: { _controller: 'WorldiaTextmasterBundle:Job:compare' }

worldia_textmaster_job_validate:
    methods:  [GET, POST]
    path:     /jobs/{id}/validate/{action}
    defaults: { _controller: 'WorldiaTextmasterBundle:Job:validate', action: accept }
    requirements:
        action:  accept|reject
