worldia_textmaster_project_index:
    methods:  [GET]
    path:     /projects
    defaults: { _controller: WorldiaTextmasterBundle:Project:index }

worldia_textmaster_project_show:
    methods:  [GET]
    path:     /projects/{id}
    defaults: { _controller: WorldiaTextmasterBundle:Project:show }

worldia_textmaster_project_update:
    methods:  [POST]
    path:     /projects
    defaults: { _controller: WorldiaTextmasterBundle:Project:callback }
