worldia_textmaster_project_index:
    methods:  [GET]
    pattern:  /projects
    defaults: { _controller: WorldiaTextmasterBundle:Project:index }

worldia_textmaster_project_show:
    methods:  [GET]
    pattern:  /projects/{id}
    defaults: { _controller: WorldiaTextmasterBundle:Project:show }

worldia_textmaster_project_update:
    methods:  [POST]
    pattern:  /projects/
    defaults: { _controller: WorldiaTextmasterBundle:Project:callback }
